# Generated by Django 4.2.6 on 2023-11-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0004_rename_product_image_product_product_image1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='Discount_Price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_image3',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.ImageField(default='default_image.png', upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.ImageField(default='default_image.png', upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.ImageField(default='default_image.png', upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='img4',
            field=models.ImageField(default='default_image.png', upload_to='product'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(default='Default Description', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Name',
            field=models.CharField(default='DefaultProductName', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
