# Generated by Django 4.2.6 on 2023-11-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0006_alter_product_img1_alter_product_img2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
