# Generated by Django 4.2.6 on 2023-11-15 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0011_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
