# Generated by Django 4.2.6 on 2023-11-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0012_remove_order_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=10)),
                ('is_expired', models.DateField(default=False)),
                ('discount_price', models.IntegerField(default=100)),
                ('minimum_amount', models.IntegerField(default=500)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
