# Generated by Django 4.2.6 on 2023-11-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0014_alter_coupon_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='is_expired',
            field=models.DateField(),
        ),
    ]
