# Generated by Django 4.2.6 on 2023-11-25 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0015_alter_coupon_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_expired',
        ),
    ]
