# Generated by Django 4.2.6 on 2023-11-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0016_remove_coupon_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
