# Generated by Django 4.2.6 on 2023-11-29 04:06

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0019_alter_image_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('img4', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
    ]
