# Generated by Django 4.2.6 on 2023-11-29 04:07

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0020_alter_image_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='cropping',
        ),
        migrations.AddField(
            model_name='image',
            name='cropping1',
            field=image_cropping.fields.ImageRatioField('img1', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping1'),
        ),
        migrations.AddField(
            model_name='image',
            name='cropping2',
            field=image_cropping.fields.ImageRatioField('img2', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping2'),
        ),
        migrations.AddField(
            model_name='image',
            name='cropping3',
            field=image_cropping.fields.ImageRatioField('img3', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping3'),
        ),
        migrations.AddField(
            model_name='image',
            name='cropping4',
            field=image_cropping.fields.ImageRatioField('img4', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping4'),
        ),
    ]
