# Generated by Django 4.2.6 on 2023-12-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0024_alter_coupon_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateField(null=True),
        ),
    ]
