# Generated by Django 4.2.6 on 2023-12-02 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0025_coupon_valid_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='valid_from',
        ),
    ]
