# Generated by Django 4.2.6 on 2023-12-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0026_remove_coupon_valid_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied_coupon',
            name='applied',
            field=models.BooleanField(default=True),
        ),
    ]
