# Generated by Django 4.2.6 on 2023-12-11 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0028_alter_product_img2_alter_product_img3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_offer', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.category')),
            ],
        ),
    ]
