# Generated by Django 4.2.6 on 2023-12-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0029_categoryoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
