# Generated by Django 4.2.6 on 2023-12-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0030_alter_categoryoffer_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='d_price',
            field=models.IntegerField(default=0),
        ),
    ]
