# Generated by Django 4.2.6 on 2023-12-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0033_productoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimg', models.ImageField(default=None, null=True, upload_to='product')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(default='Default Description', max_length=100)),
                ('link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
