# Generated by Django 4.2.6 on 2023-11-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_address_phone_remove_address_post_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='flag',
        ),
    ]
