# Generated by Django 4.2.6 on 2023-11-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_status',
            field=models.CharField(default=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True), max_length=10),
        ),
    ]
