# Generated by Django 4.2.6 on 2023-12-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_order_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_return_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_return_requested',
            field=models.BooleanField(default=False),
        ),
    ]
