# Generated by Django 4.2.6 on 2023-12-08 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_remove_order_is_return_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.order'),
        ),
    ]
