# Generated by Django 4.2.6 on 2023-12-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_referralreward_delete_referal_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferralReward',
        ),
    ]
