# Generated by Django 4.2.6 on 2023-12-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_delete_referralreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
