# Generated by Django 4.2.6 on 2023-12-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_cartitem_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='transaction_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
