# Generated by Django 4.2.6 on 2023-12-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_alter_wallet_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
