# Generated by Django 4.2.6 on 2023-12-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='referral',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.referral'),
        ),
    ]
